D1_QUESTIONS = [
    # --- Subdomain 1.1: Basic AI concepts and terminologies (5 questions) ---
    {
        "id": "d1_001",
        "domain": 1,
        "subdomain": "1.1",
        "difficulty": "foundational",
        "text": "A data scientist has a dataset of historical house prices that includes features such as square footage, number of bedrooms, and sale price. They want to train a model to predict the sale price of new houses. Which type of machine learning is MOST appropriate?",
        "choices": [
            "Unsupervised learning",
            "Supervised learning",
            "Reinforcement learning",
            "Self-supervised learning",
        ],
        "correct_index": 1,
        "explanation": "Supervised learning is used when you have labeled training data — in this case, historical houses with known sale prices. The model learns to map input features (square footage, bedrooms) to the target label (sale price). Unsupervised learning would be used when there are no labels, and reinforcement learning involves an agent learning through rewards and penalties in an environment.",
    },
    {
        "id": "d1_002",
        "domain": 1,
        "subdomain": "1.1",
        "difficulty": "foundational",
        "text": "A retail company wants to group its customers into segments based on purchasing behavior, but it does not have predefined categories. Which type of machine learning should they use?",
        "choices": [
            "Supervised classification",
            "Supervised regression",
            "Unsupervised learning (clustering)",
            "Reinforcement learning",
        ],
        "correct_index": 2,
        "explanation": "Unsupervised learning, specifically clustering, is designed to find hidden patterns or groupings in data without predefined labels. Since the company does not have predefined customer categories, clustering algorithms like k-means can discover natural segments. Supervised learning would require labeled examples of each customer segment.",
    },
    {
        "id": "d1_003",
        "domain": 1,
        "subdomain": "1.1",
        "difficulty": "intermediate",
        "text": "Which statement BEST describes the relationship between artificial intelligence, machine learning, and deep learning?",
        "choices": [
            "Deep learning is a superset that contains both AI and machine learning.",
            "Machine learning and deep learning are separate, unrelated fields within AI.",
            "AI is the broadest concept, machine learning is a subset of AI, and deep learning is a subset of machine learning.",
            "AI and machine learning are the same thing, while deep learning is a newer replacement for both.",
        ],
        "correct_index": 2,
        "explanation": "AI is the broadest field concerned with creating intelligent systems. Machine learning is a subset of AI that focuses on systems that learn from data. Deep learning is a further subset of ML that uses multi-layered neural networks to learn complex representations. This nested relationship is a foundational concept for the AIF-C01 exam.",
    },
    {
        "id": "d1_004",
        "domain": 1,
        "subdomain": "1.1",
        "difficulty": "intermediate",
        "text": "A game-playing AI agent learns to maximize its score by trying different moves and receiving feedback on whether each move increased or decreased its score. Which type of machine learning does this describe?",
        "choices": [
            "Supervised learning with regression",
            "Unsupervised learning with dimensionality reduction",
            "Reinforcement learning",
            "Semi-supervised learning",
        ],
        "correct_index": 2,
        "explanation": "Reinforcement learning involves an agent that interacts with an environment, takes actions, and learns from rewards or penalties to maximize cumulative reward. Game-playing scenarios are a classic application, where the agent learns a strategy through trial and error. This differs from supervised learning, which requires labeled training examples rather than reward signals.",
    },
    {
        "id": "d1_005",
        "domain": 1,
        "subdomain": "1.1",
        "difficulty": "foundational",
        "text": "Which of the following BEST describes natural language processing (NLP)?",
        "choices": [
            "A branch of AI focused on enabling computers to interpret and generate human language",
            "A technique for training neural networks on image datasets",
            "A method for reinforcement learning agents to communicate with each other",
            "A database technology used to store unstructured text data",
        ],
        "correct_index": 0,
        "explanation": "Natural language processing (NLP) is the branch of artificial intelligence that deals with the interaction between computers and human language. It encompasses tasks such as text classification, sentiment analysis, machine translation, and language generation. Computer vision, not NLP, deals with image interpretation.",
    },
    # --- Subdomain 1.2: Practical use cases for AI (5 questions) ---
    {
        "id": "d1_006",
        "domain": 1,
        "subdomain": "1.2",
        "difficulty": "foundational",
        "text": "An e-commerce company wants to suggest products to customers based on their browsing history and previous purchases. Which AI use case does this describe?",
        "choices": [
            "Fraud detection",
            "Recommendation system",
            "Demand forecasting",
            "Optical character recognition",
        ],
        "correct_index": 1,
        "explanation": "Recommendation systems analyze user behavior (browsing history, purchase patterns, ratings) to suggest relevant items. This is one of the most common commercial AI applications, used by companies like Amazon and Netflix. Fraud detection focuses on identifying suspicious transactions, while demand forecasting predicts future product demand.",
    },
    {
        "id": "d1_007",
        "domain": 1,
        "subdomain": "1.2",
        "difficulty": "intermediate",
        "text": "A financial institution processes millions of credit card transactions daily and needs to identify potentially fraudulent transactions in near real-time. Which combination of AI techniques would be MOST effective?",
        "choices": [
            "Image recognition and natural language processing",
            "Anomaly detection and supervised classification",
            "Text summarization and machine translation",
            "Reinforcement learning and generative AI",
        ],
        "correct_index": 1,
        "explanation": "Fraud detection typically combines anomaly detection (to flag transactions that deviate from normal patterns) with supervised classification (trained on labeled examples of fraudulent and legitimate transactions). This combination catches both known fraud patterns and novel suspicious activity. Image recognition and NLP are not directly relevant to transaction-based fraud detection.",
    },
    {
        "id": "d1_008",
        "domain": 1,
        "subdomain": "1.2",
        "difficulty": "foundational",
        "text": "A logistics company wants to predict how much inventory to stock for the upcoming holiday season. Which AI use case BEST fits this need?",
        "choices": [
            "Chatbot development",
            "Image classification",
            "Time-series forecasting",
            "Sentiment analysis",
        ],
        "correct_index": 2,
        "explanation": "Time-series forecasting uses historical data patterns to predict future values over time, making it ideal for demand and inventory planning. The model learns seasonal trends, growth patterns, and other temporal factors to generate predictions. Chatbots handle conversational interactions, while image classification and sentiment analysis address different problem types entirely.",
    },
    {
        "id": "d1_009",
        "domain": 1,
        "subdomain": "1.2",
        "difficulty": "intermediate",
        "text": "A healthcare company wants to use AI to analyze medical images such as X-rays and MRIs to assist radiologists in detecting abnormalities. Which AI capability is MOST relevant?",
        "choices": [
            "Natural language processing",
            "Computer vision and image recognition",
            "Speech recognition",
            "Recommendation engines",
        ],
        "correct_index": 1,
        "explanation": "Computer vision and image recognition techniques, particularly convolutional neural networks (CNNs), are well suited for analyzing medical images. These models can identify patterns and abnormalities in X-rays, MRIs, and CT scans that may be difficult for the human eye to detect. NLP and speech recognition deal with text and audio, not visual data.",
    },
    {
        "id": "d1_010",
        "domain": 1,
        "subdomain": "1.2",
        "difficulty": "foundational",
        "text": "A company wants to deploy an AI-powered virtual assistant on its website that can answer customer questions 24/7 in natural language. Which AI use case does this describe?",
        "choices": [
            "Predictive maintenance",
            "Chatbot / conversational AI",
            "Anomaly detection",
            "Image segmentation",
        ],
        "correct_index": 1,
        "explanation": "Chatbots and conversational AI systems use NLP to understand user questions and generate helpful responses. They are a widely adopted AI use case for customer service, enabling 24/7 support without human agents for common inquiries. Predictive maintenance focuses on predicting equipment failures, which is unrelated to customer-facing conversation.",
    },
    # --- Subdomain 1.3: ML development lifecycle (5 questions) ---
    {
        "id": "d1_011",
        "domain": 1,
        "subdomain": "1.3",
        "difficulty": "foundational",
        "text": "In the machine learning development lifecycle, what is the primary purpose of feature engineering?",
        "choices": [
            "Deploying the trained model to a production endpoint",
            "Selecting and transforming raw data into input variables that improve model performance",
            "Splitting the dataset into training and test sets",
            "Monitoring model performance after deployment",
        ],
        "correct_index": 1,
        "explanation": "Feature engineering is the process of selecting, creating, and transforming raw data attributes into features that help the ML model learn more effectively. Good features can dramatically improve model accuracy, while poor features can hinder learning. This step occurs after data collection and before model training in the ML lifecycle.",
    },
    {
        "id": "d1_012",
        "domain": 1,
        "subdomain": "1.3",
        "difficulty": "intermediate",
        "text": "A binary classification model has the following results: out of 100 actual positives, it correctly identified 90 (true positives) and missed 10 (false negatives). Out of 100 actual negatives, it correctly identified 80 (true negatives) and incorrectly flagged 20 (false positives). What is the model's recall?",
        "choices": [
            "80%",
            "82%",
            "90%",
            "81.8%",
        ],
        "correct_index": 2,
        "explanation": "Recall (also called sensitivity or true positive rate) measures the proportion of actual positives that the model correctly identified: TP / (TP + FN) = 90 / (90 + 10) = 90%. Recall is especially important when the cost of missing a positive case is high, such as in medical diagnoses or fraud detection. Precision, by contrast, would be TP / (TP + FP) = 90 / (90 + 20) = 81.8%.",
    },
    {
        "id": "d1_013",
        "domain": 1,
        "subdomain": "1.3",
        "difficulty": "intermediate",
        "text": "A machine learning team notices that their model performs extremely well on the training data but poorly on the validation data. Which issue does this MOST likely indicate?",
        "choices": [
            "Underfitting",
            "Overfitting",
            "Data leakage from the test set",
            "Insufficient feature engineering",
        ],
        "correct_index": 1,
        "explanation": "Overfitting occurs when a model memorizes the training data, including its noise and peculiarities, rather than learning generalizable patterns. This results in high training accuracy but poor performance on unseen data. Solutions include adding regularization, using more training data, reducing model complexity, or applying techniques like dropout and early stopping.",
    },
    {
        "id": "d1_014",
        "domain": 1,
        "subdomain": "1.3",
        "difficulty": "foundational",
        "text": "Which evaluation metric provides a single score that balances both precision and recall?",
        "choices": [
            "Accuracy",
            "AUC-ROC",
            "F1 score",
            "Mean squared error",
        ],
        "correct_index": 2,
        "explanation": "The F1 score is the harmonic mean of precision and recall, providing a single metric that balances both. It is particularly useful when dealing with imbalanced datasets where accuracy alone can be misleading. AUC-ROC measures the trade-off between true positive rate and false positive rate across thresholds, while mean squared error is used for regression tasks.",
    },
    {
        "id": "d1_015",
        "domain": 1,
        "subdomain": "1.3",
        "difficulty": "intermediate",
        "text": "Which practice in the ML lifecycle focuses on automating model retraining, testing, and deployment pipelines to ensure models remain accurate and up to date?",
        "choices": [
            "Feature engineering",
            "Hyperparameter tuning",
            "MLOps",
            "Exploratory data analysis",
        ],
        "correct_index": 2,
        "explanation": "MLOps (Machine Learning Operations) applies DevOps practices to machine learning workflows, automating the end-to-end lifecycle including data validation, model training, testing, deployment, and monitoring. It ensures reproducibility, scalability, and reliability of ML systems in production. Feature engineering and hyperparameter tuning are individual steps within the lifecycle, not the overarching operational framework.",
    },
    # --- Subdomain 1.4: AWS AI/ML services (5 questions) ---
    {
        "id": "d1_016",
        "domain": 1,
        "subdomain": "1.4",
        "difficulty": "foundational",
        "text": "A company wants to build, train, and deploy custom machine learning models at scale on AWS. Which AWS service provides a fully managed environment for the complete ML workflow?",
        "choices": [
            "Amazon Comprehend",
            "Amazon SageMaker",
            "Amazon Rekognition",
            "Amazon Polly",
        ],
        "correct_index": 1,
        "explanation": "Amazon SageMaker is a fully managed service that provides tools for every step of the ML lifecycle, including data labeling, model building, training, tuning, and deployment. It supports built-in algorithms, custom code, and popular ML frameworks. Comprehend, Rekognition, and Polly are AI services for specific tasks (NLP, image analysis, and text-to-speech) that do not require building custom models.",
    },
    {
        "id": "d1_017",
        "domain": 1,
        "subdomain": "1.4",
        "difficulty": "foundational",
        "text": "An organization needs to automatically extract text and structured data from scanned documents such as forms and invoices. Which AWS service should they use?",
        "choices": [
            "Amazon Translate",
            "Amazon Textract",
            "Amazon Polly",
            "Amazon Lex",
        ],
        "correct_index": 1,
        "explanation": "Amazon Textract uses machine learning to automatically extract text, handwriting, and structured data (tables, forms) from scanned documents. It goes beyond simple OCR by understanding the structure and relationships within documents. Amazon Translate handles language translation, Polly converts text to speech, and Lex builds conversational chatbot interfaces.",
    },
    {
        "id": "d1_018",
        "domain": 1,
        "subdomain": "1.4",
        "difficulty": "intermediate",
        "text": "A media company wants to automatically detect objects, scenes, and faces in images and videos uploaded by users. Which AWS service is purpose-built for this?",
        "choices": [
            "Amazon Personalize",
            "Amazon Forecast",
            "Amazon Rekognition",
            "Amazon Comprehend",
        ],
        "correct_index": 2,
        "explanation": "Amazon Rekognition is a fully managed computer vision service that can identify objects, people, text, scenes, and activities in images and videos. It also provides facial analysis and facial recognition capabilities. Amazon Personalize is for recommendations, Forecast is for time-series predictions, and Comprehend is an NLP service for text analysis.",
    },
    {
        "id": "d1_019",
        "domain": 1,
        "subdomain": "1.4",
        "difficulty": "intermediate",
        "text": "A company wants to build a conversational interface for its mobile app that understands voice and text input and can handle multi-turn conversations. Which AWS service should they use?",
        "choices": [
            "Amazon Lex",
            "Amazon Polly",
            "Amazon Transcribe",
            "Amazon Comprehend",
        ],
        "correct_index": 0,
        "explanation": "Amazon Lex provides the technology to build conversational interfaces (chatbots) that understand natural language voice and text input. It supports multi-turn conversations with context management and integrates with other AWS services. Amazon Polly converts text to speech (output only), Transcribe converts speech to text, and Comprehend analyzes text for insights but does not build conversational flows.",
    },
    {
        "id": "d1_020",
        "domain": 1,
        "subdomain": "1.4",
        "difficulty": "foundational",
        "text": "A streaming service wants to provide personalized content recommendations to each user based on their viewing history. Which AWS AI service is specifically designed for this use case?",
        "choices": [
            "Amazon Forecast",
            "Amazon Personalize",
            "Amazon Comprehend",
            "Amazon SageMaker",
        ],
        "correct_index": 1,
        "explanation": "Amazon Personalize is purpose-built for creating real-time personalized recommendation systems. It uses the same technology as Amazon.com to generate recommendations based on user behavior data. While SageMaker could be used to build a custom recommendation model, Personalize provides this capability as a managed service with no ML expertise required.",
    },
]

D2_QUESTIONS = [
    # --- Subdomain 2.1: Foundation models and architectures (6 questions) ---
    {
        "id": "d2_001",
        "domain": 2,
        "subdomain": "2.1",
        "difficulty": "foundational",
        "text": "What is a foundation model in the context of generative AI?",
        "choices": [
            "A small, task-specific model trained on a narrow dataset for a single purpose",
            "A large model pre-trained on broad data that can be adapted to a wide range of downstream tasks",
            "A model that can only generate text and cannot process other data types",
            "A model architecture exclusively used for image generation",
        ],
        "correct_index": 1,
        "explanation": "A foundation model is a large AI model pre-trained on vast, diverse datasets that serves as a base for many different tasks. These models learn general-purpose representations that can be fine-tuned or prompted for specific applications such as text generation, summarization, classification, and more. The term was popularized by Stanford researchers to describe models like GPT and BERT.",
    },
    {
        "id": "d2_002",
        "domain": 2,
        "subdomain": "2.1",
        "difficulty": "intermediate",
        "text": "Which architecture is the basis for most modern large language models (LLMs) such as GPT and Claude?",
        "choices": [
            "Recurrent Neural Network (RNN)",
            "Convolutional Neural Network (CNN)",
            "Transformer",
            "Generative Adversarial Network (GAN)",
        ],
        "correct_index": 2,
        "explanation": "The Transformer architecture, introduced in the 2017 paper 'Attention Is All You Need,' is the foundation of most modern LLMs. Its self-attention mechanism allows the model to process all tokens in a sequence in parallel and capture long-range dependencies efficiently. RNNs process sequences sequentially and struggle with long contexts, while CNNs are primarily used for image processing and GANs are used for adversarial generation.",
    },
    {
        "id": "d2_003",
        "domain": 2,
        "subdomain": "2.1",
        "difficulty": "foundational",
        "text": "In the context of large language models, what is a 'token'?",
        "choices": [
            "A unique API key used to authenticate requests to the model",
            "A unit of text (such as a word, subword, or character) that the model processes",
            "A measure of the model's accuracy on a benchmark",
            "A type of neural network layer used in transformers",
        ],
        "correct_index": 1,
        "explanation": "A token is the basic unit of text that an LLM processes. Depending on the tokenizer, a token may represent a whole word, a subword, a character, or punctuation. For example, the word 'unhappiness' might be split into tokens like 'un', 'happiness'. Understanding tokens is important because model context windows and pricing are typically measured in tokens.",
    },
    {
        "id": "d2_004",
        "domain": 2,
        "subdomain": "2.1",
        "difficulty": "intermediate",
        "text": "When someone says a model has '70 billion parameters,' what does this refer to?",
        "choices": [
            "The number of training examples the model was trained on",
            "The maximum number of tokens the model can process in a single request",
            "The number of adjustable weights the model learned during training",
            "The number of different languages the model supports",
        ],
        "correct_index": 2,
        "explanation": "Parameters are the internal weights and biases that a neural network learns during training. A 70-billion-parameter model has 70 billion adjustable numerical values that collectively encode the knowledge and capabilities the model acquired. Generally, more parameters allow a model to capture more complex patterns, though model architecture and training data quality also play critical roles.",
    },
    {
        "id": "d2_005",
        "domain": 2,
        "subdomain": "2.1",
        "difficulty": "intermediate",
        "text": "Which type of generative AI model creates images by iteratively removing noise from a random starting point, guided by a text or image prompt?",
        "choices": [
            "Transformer decoder model",
            "Generative Adversarial Network (GAN)",
            "Diffusion model",
            "Variational autoencoder (VAE)",
        ],
        "correct_index": 2,
        "explanation": "Diffusion models generate images through a denoising process: they start with random noise and gradually refine it into a coherent image guided by conditioning signals like text prompts. Models like Stable Diffusion and DALL-E use this approach. GANs use a generator-discriminator pair, while VAEs use an encoder-decoder structure with a latent space.",
    },
    {
        "id": "d2_006",
        "domain": 2,
        "subdomain": "2.1",
        "difficulty": "foundational",
        "text": "What is 'inference' in the context of a deployed machine learning model?",
        "choices": [
            "The process of training the model on new data",
            "The process of using a trained model to generate predictions or outputs from new inputs",
            "The process of evaluating the model against a benchmark dataset",
            "The process of converting the model from one framework to another",
        ],
        "correct_index": 1,
        "explanation": "Inference is the phase where a trained model is used to make predictions or generate outputs based on new, unseen input data. For example, when you send a prompt to an LLM and receive a response, the model is performing inference. This is distinct from training, where the model's parameters are being updated by learning from data.",
    },
    # --- Subdomain 2.2: Prompt engineering (6 questions) ---
    {
        "id": "d2_007",
        "domain": 2,
        "subdomain": "2.2",
        "difficulty": "foundational",
        "text": "A developer sends the following prompt to an LLM: 'Translate the following English text to French: Hello, how are you?' without providing any examples. Which prompting technique does this illustrate?",
        "choices": [
            "Few-shot prompting",
            "Chain-of-thought prompting",
            "Zero-shot prompting",
            "Retrieval-augmented generation",
        ],
        "correct_index": 2,
        "explanation": "Zero-shot prompting provides the model with instructions for a task without giving any examples. The model relies solely on its pre-trained knowledge to perform the task. This is the simplest prompting approach and works well for tasks that LLMs commonly encountered during training. Few-shot prompting would include one or more examples of the desired input-output pattern.",
    },
    {
        "id": "d2_008",
        "domain": 2,
        "subdomain": "2.2",
        "difficulty": "foundational",
        "text": "A prompt includes three examples of customer reviews labeled as 'positive' or 'negative' before asking the model to classify a new review. Which prompting technique is being used?",
        "choices": [
            "Zero-shot prompting",
            "Few-shot prompting",
            "Chain-of-thought prompting",
            "Self-consistency prompting",
        ],
        "correct_index": 1,
        "explanation": "Few-shot prompting provides the model with a small number of examples (typically 1-5) of the desired task within the prompt before presenting the actual query. This helps the model understand the expected format and behavior. It is more effective than zero-shot for tasks where the model might be ambiguous about the desired output format or labeling scheme.",
    },
    {
        "id": "d2_009",
        "domain": 2,
        "subdomain": "2.2",
        "difficulty": "intermediate",
        "text": "A developer wants an LLM to solve a math word problem. Instead of asking for the answer directly, the developer instructs the model to 'explain your reasoning step by step before giving the final answer.' Which prompting technique does this represent?",
        "choices": [
            "Zero-shot prompting",
            "Few-shot prompting",
            "Chain-of-thought prompting",
            "Prompt chaining",
        ],
        "correct_index": 2,
        "explanation": "Chain-of-thought (CoT) prompting encourages the model to break down complex problems into intermediate reasoning steps before arriving at a final answer. This technique significantly improves performance on tasks requiring logical reasoning, math, and multi-step problem solving. By making the reasoning process explicit, the model is less likely to skip steps or make logical errors.",
    },
    {
        "id": "d2_010",
        "domain": 2,
        "subdomain": "2.2",
        "difficulty": "intermediate",
        "text": "When configuring an LLM, what effect does increasing the 'temperature' parameter have on the model's output?",
        "choices": [
            "It makes the output more deterministic and focused on the most likely tokens",
            "It makes the output more random and creative by flattening the probability distribution",
            "It increases the maximum number of tokens the model can generate",
            "It speeds up the inference time of the model",
        ],
        "correct_index": 1,
        "explanation": "Temperature controls the randomness of the model's output. A higher temperature (e.g., 1.0 or above) flattens the probability distribution over tokens, making less likely tokens more probable and producing more diverse, creative outputs. A lower temperature (e.g., 0.1) sharpens the distribution, making the model more deterministic and focused on high-probability tokens. Temperature does not affect context length or inference speed.",
    },
    {
        "id": "d2_011",
        "domain": 2,
        "subdomain": "2.2",
        "difficulty": "intermediate",
        "text": "What is the purpose of a 'system prompt' when interacting with a large language model?",
        "choices": [
            "To provide the model with the user's specific question or request",
            "To set the model's overall behavior, persona, and constraints before user interaction begins",
            "To fine-tune the model's weights on new training data",
            "To encrypt the communication between the user and the model",
        ],
        "correct_index": 1,
        "explanation": "A system prompt is a special instruction given to the model that defines its role, personality, constraints, and behavioral guidelines for the conversation. For example, it might instruct the model to act as a helpful customer service agent that only answers questions about a specific product. System prompts are processed before user messages and help steer the model's responses consistently throughout a session.",
    },
    {
        "id": "d2_012",
        "domain": 2,
        "subdomain": "2.2",
        "difficulty": "foundational",
        "text": "A developer wants their LLM application to produce highly predictable, consistent outputs for a customer-facing FAQ bot. Which approach to the temperature and top-p settings would be MOST appropriate?",
        "choices": [
            "High temperature and high top-p for maximum creativity",
            "Low temperature and low top-p for more deterministic output",
            "High temperature and low top-p to balance creativity and consistency",
            "Temperature and top-p settings have no effect on output consistency",
        ],
        "correct_index": 1,
        "explanation": "For use cases requiring consistent, factual, and predictable outputs like FAQ bots, using low temperature and low top-p values restricts the model to choosing from the most probable tokens. This reduces variability between responses to the same question. High temperature and top-p would introduce more randomness, which is better suited for creative tasks like story writing.",
    },
    # --- Subdomain 2.3: Fine-tuning and customization (6 questions) ---
    {
        "id": "d2_013",
        "domain": 2,
        "subdomain": "2.3",
        "difficulty": "foundational",
        "text": "What is the primary difference between pre-training and fine-tuning a large language model?",
        "choices": [
            "Pre-training uses labeled data while fine-tuning uses unlabeled data",
            "Pre-training trains the model from scratch on a large general corpus, while fine-tuning adapts an already pre-trained model to a specific task or domain",
            "Fine-tuning always requires more compute resources than pre-training",
            "Pre-training can only be done once, and the model cannot be further pre-trained",
        ],
        "correct_index": 1,
        "explanation": "Pre-training is the initial, resource-intensive phase where a model learns general language understanding from massive, diverse datasets. Fine-tuning then takes this pre-trained model and further trains it on a smaller, task-specific or domain-specific dataset to adapt its behavior. Fine-tuning is much less resource-intensive than pre-training because it starts from an already knowledgeable model.",
    },
    {
        "id": "d2_014",
        "domain": 2,
        "subdomain": "2.3",
        "difficulty": "intermediate",
        "text": "What is Reinforcement Learning from Human Feedback (RLHF) used for in the context of large language models?",
        "choices": [
            "Pre-training the model on internet-scale text data",
            "Aligning the model's outputs with human preferences for helpfulness, harmlessness, and honesty",
            "Increasing the model's parameter count to improve capacity",
            "Converting the model from one programming framework to another",
        ],
        "correct_index": 1,
        "explanation": "RLHF is a technique used after initial pre-training to align a model's behavior with human values and preferences. Human evaluators rank model outputs, and a reward model is trained on these rankings. The language model is then fine-tuned using reinforcement learning to maximize the reward model's score. This process helps produce outputs that are more helpful, accurate, and safe.",
    },
    {
        "id": "d2_015",
        "domain": 2,
        "subdomain": "2.3",
        "difficulty": "foundational",
        "text": "Which technique allows a foundation model to access and incorporate external, up-to-date information that was not part of its training data when generating responses?",
        "choices": [
            "Transfer learning",
            "Reinforcement learning from human feedback (RLHF)",
            "Retrieval-Augmented Generation (RAG)",
            "Prompt engineering with few-shot examples",
        ],
        "correct_index": 2,
        "explanation": "Retrieval-Augmented Generation (RAG) combines a language model with an external knowledge retrieval system. When a query is received, relevant documents are retrieved from a knowledge base and included in the prompt context, enabling the model to generate answers grounded in current, domain-specific information. This approach is especially valuable for keeping responses up to date without retraining the model.",
    },
    {
        "id": "d2_016",
        "domain": 2,
        "subdomain": "2.3",
        "difficulty": "intermediate",
        "text": "A company wants to customize a foundation model to use its internal technical documentation when answering employee questions. The documentation is updated weekly. Which approach is MOST practical?",
        "choices": [
            "Re-pre-train the foundation model from scratch every week",
            "Fine-tune the model weekly on the updated documentation",
            "Use Retrieval-Augmented Generation (RAG) with a regularly updated vector database of the documentation",
            "Increase the model's temperature parameter to generate more creative answers",
        ],
        "correct_index": 2,
        "explanation": "RAG with a vector database is the most practical approach because the documentation can be re-indexed weekly without modifying the model itself. This avoids the high cost and complexity of frequent re-training or fine-tuning. The model retrieves relevant document chunks at query time, ensuring responses reflect the latest content. Adjusting temperature affects randomness, not knowledge currency.",
    },
    {
        "id": "d2_017",
        "domain": 2,
        "subdomain": "2.3",
        "difficulty": "intermediate",
        "text": "What is transfer learning in the context of machine learning?",
        "choices": [
            "Moving a trained model from one cloud provider to another",
            "Using knowledge learned from one task to improve performance on a different but related task",
            "Transferring data between training and validation datasets",
            "Converting a model from supervised learning to unsupervised learning",
        ],
        "correct_index": 1,
        "explanation": "Transfer learning leverages knowledge that a model has gained from being trained on one task (or large dataset) and applies it to a different but related task. This is the core principle behind using foundation models: a model pre-trained on general text can be adapted to specialized tasks like medical document classification with relatively little additional training data. It significantly reduces the data and compute requirements for new tasks.",
    },
    {
        "id": "d2_018",
        "domain": 2,
        "subdomain": "2.3",
        "difficulty": "foundational",
        "text": "Which customization approach modifies the actual model weights to adapt a foundation model's behavior for a specific domain?",
        "choices": [
            "Prompt engineering",
            "Retrieval-Augmented Generation (RAG)",
            "Fine-tuning",
            "Adjusting the inference temperature",
        ],
        "correct_index": 2,
        "explanation": "Fine-tuning is the only approach among these options that modifies the model's internal weights. It involves additional training on domain-specific data, which updates the model parameters to better reflect the target domain's language, concepts, and patterns. Prompt engineering and RAG influence outputs without changing weights, and temperature adjustment only affects the sampling strategy during inference.",
    },
    # --- Subdomain 2.4: AWS generative AI services (6 questions) ---
    {
        "id": "d2_019",
        "domain": 2,
        "subdomain": "2.4",
        "difficulty": "foundational",
        "text": "Which AWS service provides access to foundation models from multiple providers through a single API, enabling developers to build generative AI applications?",
        "choices": [
            "Amazon SageMaker",
            "Amazon Bedrock",
            "Amazon Comprehend",
            "Amazon Rekognition",
        ],
        "correct_index": 1,
        "explanation": "Amazon Bedrock is a fully managed service that offers a choice of foundation models from leading AI companies (such as Anthropic, Meta, AI21 Labs, Cohere, and Stability AI) through a single API. It allows developers to build and scale generative AI applications without managing infrastructure. SageMaker is a broader ML platform for building custom models, while Comprehend and Rekognition are task-specific AI services.",
    },
    {
        "id": "d2_020",
        "domain": 2,
        "subdomain": "2.4",
        "difficulty": "intermediate",
        "text": "A company wants to use Anthropic's Claude model on AWS for a customer support chatbot. Which AWS service provides managed access to Claude without requiring the company to host the model themselves?",
        "choices": [
            "Amazon Lex",
            "Amazon Bedrock",
            "Amazon SageMaker JumpStart",
            "AWS Lambda",
        ],
        "correct_index": 1,
        "explanation": "Amazon Bedrock provides fully managed, serverless access to Anthropic's Claude models (along with other foundation models) via API. Companies can use Claude through Bedrock without provisioning or managing any infrastructure. Amazon Lex is a chatbot-building service with a different architecture, and while SageMaker JumpStart offers some models, Bedrock is the primary service for accessing Claude on AWS.",
    },
    {
        "id": "d2_021",
        "domain": 2,
        "subdomain": "2.4",
        "difficulty": "foundational",
        "text": "Which of the following is Amazon's own family of foundation models available through Amazon Bedrock?",
        "choices": [
            "Llama",
            "Claude",
            "Amazon Titan",
            "Stable Diffusion",
        ],
        "correct_index": 2,
        "explanation": "Amazon Titan is Amazon's own family of foundation models, available exclusively through Amazon Bedrock. The Titan family includes models for text generation, embeddings, and image generation. Llama is developed by Meta, Claude by Anthropic, and Stable Diffusion by Stability AI — all are third-party models also available on Bedrock.",
    },
    {
        "id": "d2_022",
        "domain": 2,
        "subdomain": "2.4",
        "difficulty": "intermediate",
        "text": "A developer wants to quickly prototype a generative AI application using foundation models without writing any code. Which AWS tool allows no-code experimentation with foundation models in Amazon Bedrock?",
        "choices": [
            "Amazon SageMaker Studio",
            "AWS CloudFormation",
            "Amazon Bedrock Playground (PartyRock)",
            "Amazon CodeWhisperer",
        ],
        "correct_index": 2,
        "explanation": "PartyRock is an Amazon Bedrock Playground that provides a no-code, shareable environment for experimenting with foundation models. Users can build generative AI applications by describing what they want in natural language, making it ideal for rapid prototyping and learning. SageMaker Studio is a code-based ML IDE, and CloudFormation is an infrastructure-as-code service.",
    },
    {
        "id": "d2_023",
        "domain": 2,
        "subdomain": "2.4",
        "difficulty": "intermediate",
        "text": "Which foundation model providers are available through Amazon Bedrock? (Select the BEST answer.)",
        "choices": [
            "Only Amazon's own Titan models",
            "Only open-source models from Hugging Face",
            "Multiple providers including Anthropic (Claude), Meta (Llama), AI21 Labs, Cohere, and Stability AI, in addition to Amazon Titan",
            "Only Anthropic's Claude models and Amazon Titan",
        ],
        "correct_index": 2,
        "explanation": "Amazon Bedrock offers a diverse selection of foundation models from multiple providers: Anthropic (Claude), Meta (Llama), AI21 Labs (Jurassic), Cohere (Command), Stability AI (Stable Diffusion), and Amazon's own Titan models. This multi-provider approach lets customers choose the best model for their specific use case. Bedrock is not limited to Amazon's own models or any single provider.",
    },
    {
        "id": "d2_024",
        "domain": 2,
        "subdomain": "2.4",
        "difficulty": "foundational",
        "text": "A company wants to customize a foundation model in Amazon Bedrock with its own proprietary data while ensuring that the data is not used to train the base model and remains private. Does Amazon Bedrock support this?",
        "choices": [
            "No, all data sent to Bedrock is used to improve the base foundation models",
            "Yes, Bedrock supports model customization (fine-tuning) with customer data that remains private and is not used to train the base models",
            "Only if the company uses Amazon Titan models; third-party models cannot be customized",
            "Data privacy is only guaranteed if the company uses a VPC endpoint, otherwise data may be shared",
        ],
        "correct_index": 1,
        "explanation": "Amazon Bedrock supports model customization through fine-tuning with customer data, and AWS guarantees that customer data is not used to train or improve the base foundation models. Customer data remains private and is encrypted in transit and at rest. This privacy commitment is a key selling point of Bedrock for enterprise customers with sensitive data.",
    },
]
